name: Workflow

on: [push]

jobs:
  build-debug:
    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Build App
      run: dotnet build BlackJack/BlackJack.csproj

  build-release:
    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Build App
      run: dotnet build BlackJack/BlackJack.csproj

  test-debug:
    needs: build-debug
    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Run tests
      run: dotnet test BlackJack.Tests/BlackJack.Tests.csproj --configuration Debug\
          --collect:"XPlat Code Coverage"\
          --results-directory ./Artifacts/

  test-release:
    needs: build-release
    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Run tests
      run: dotnet test BlackJack.Tests/BlackJack.Tests.csproj --configuration Release\
          --collect:"XPlat Code Coverage"\
          --results-directory ./Artifacts/

